[package]
cairo-version = "2.6.3"
name = "dojo_starter"
version = "0.7.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.1" }
starknet = "2.6.3"

[[target.dojo]] 
[[target.starknet-contract]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/nfthunt/katana/"
# Default account for katana with seed = 0
account_address = "0x730e16cb0104dd30996082de23488ef7c36e78061ad5d34cc255c48ede04313"
private_key = "0x7fcc2db753d5830c5d9c28b37dbc65a5a39b1d1ea8de546f50f087ed64acd3e"
world_address = "0x00b4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"  # Update this line with your world address

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
