[package]
cairo-version = "2.6.3"
name = "dojo_starter"
version = "0.7.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.0" }
starknet = "2.6.3"

[[target.dojo]] 
[[target.starknet-contract]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/nfthunt/katana/"
# Default account for katana with seed = 0
account_address = "0x3412227dd64be029af65be6877df411aa9165ec57bbce3cafbb5dd02be3c5ca"
private_key = "0x7c811d902aa24f38335a7bd7372f012c1dcee4c1edc1bdef93d0982b58d42be"
world_address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"  # Update this line with your world address
