kind = "DojoContract"
class_hash = "0x59e0d2275a37d4052f2c1ceab6ae95d188aa37e56481e7636ed69ec9beacb3c"
original_class_hash = "0x59e0d2275a37d4052f2c1ceab6ae95d188aa37e56481e7636ed69ec9beacb3c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_token_erc20_ERC20.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::token::erc20::ERC20"
