kind = "DojoModel"
class_hash = "0x5c4830204c4015bfba9aa800d2913a62d1bbc237a75310aaab50f4c6e50aef3"
original_class_hash = "0x5c4830204c4015bfba9aa800d2913a62d1bbc237a75310aaab50f4c6e50aef3"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "character"
type = "Character"
key = false

[[members]]
name = "score"
type = "u64"
key = false

[[members]]
name = "position"
type = "Position"
key = false
