kind = "DojoModel"
class_hash = "0x48af75d0b7fd9d4165c957d18fc12f63106bd91a306a8325cdd660358756e90"
original_class_hash = "0x48af75d0b7fd9d4165c957d18fc12f63106bd91a306a8325cdd660358756e90"
abi = "manifests/dev/abis/base/models/dojo_starter_models_health_health.json"
name = "dojo_starter::models::health::health"

[[members]]
name = "entityId"
type = "ContractAddress"
key = true

[[members]]
name = "gameId"
type = "u32"
key = true

[[members]]
name = "health"
type = "u16"
key = false
