kind = "DojoModel"
class_hash = "0x2ea91e1fe576ffdbc7194fe02ae0878f77154b519c2f4c87ef15ba721233e5b"
original_class_hash = "0x2ea91e1fe576ffdbc7194fe02ae0878f77154b519c2f4c87ef15ba721233e5b"
abi = "manifests/dev/abis/base/models/dojo_starter_models_walk_directions_available.json"
name = "dojo_starter::models::walk::directions_available"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
