kind = "DojoModel"
class_hash = "0xb0d2fa96616af5d754a4ef4c60f9bc42d53c42d72d03b5d7da900c274916a"
original_class_hash = "0xb0d2fa96616af5d754a4ef4c60f9bc42d53c42d72d03b5d7da900c274916a"
abi = "manifests/dev/abis/base/models/dojo_starter_models_move_move.json"
name = "dojo_starter::models::move::move"

[[members]]
name = "entityId"
type = "ContractAddress"
key = true

[[members]]
name = "gameId"
type = "u32"
key = true

[[members]]
name = "attack"
type = "u16"
key = false

[[members]]
name = "healing"
type = "u16"
key = false
