// Generated by dojo-bindgen on Mon, 1 Jul 2024 11:39:24 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `dojo_starter::models::action::Action` model
public class Action : ModelInstance {
    [ModelField("entityId")]
    public FieldElement entityId;

    [ModelField("attack")]
    public ushort attack;

    [ModelField("healing")]
    public ushort healing;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        