// Generated by dojo-bindgen on Mon, 1 Jul 2024 11:39:24 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::walk::Direction` enum
public abstract record Direction() : Enum {
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


// Model definition for `dojo_starter::models::walk::DirectionsAvailable` model
public class DirectionsAvailable : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("directions")]
    public Direction[] directions;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        