// Generated by dojo-bindgen on Sun, 30 Jun 2024 18:44:46 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::game::GameStatus` enum
public abstract record GameStatus() : Enum {
    public record Lobby() : GameStatus;
    public record InProgress() : GameStatus;
    public record Lost() : GameStatus;
    public record Won() : GameStatus;
}


// Model definition for `dojo_starter::models::game::Game` model
public class Game : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("entityId")]
    public uint entityId;

    [ModelField("status")]
    public GameStatus status;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        