// Generated by dojo-bindgen on Sun, 30 Jun 2024 18:44:46 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::player::Character` enum
public abstract record Character() : Enum {
    public record Hunter() : Character;
}


// Model definition for `dojo_starter::models::player::Player` model
public class Player : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("character")]
    public Character character;

    [ModelField("score")]
    public ulong score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        