// Generated by dojo-bindgen on Sun, 30 Jun 2024 18:44:46 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::walk::Direction` enum
public abstract record Direction() : Enum {
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


// Model definition for `dojo_starter::models::walk::Walks` model
public class Walks : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("remaining")]
    public byte remaining;

    [ModelField("last_direction")]
    public Direction last_direction;

    [ModelField("can_move")]
    public bool can_move;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        