kind = "DojoModel"
class_hash = "0x4afb6783abec03f04382c414d919284b868985bcc86a9a2d79d5ac1a29c46eb"
original_class_hash = "0x4afb6783abec03f04382c414d919284b868985bcc86a9a2d79d5ac1a29c46eb"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[members]]
name = "address"
type = "starknet::ContractAddress"
key = true

[[members]]
name = "player"
type = "felt252"
key = false

[[members]]
name = "socre"
type = "u64"
key = false
