[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"
transaction_hash = "0xfc80fdc9ff7f1e95e970f0e5965eed399becff62e734b67d680c89603cb6a2"
block_number = 24
seed = "dojo_starter"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/third/katana"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x3610b797baec740e2fa25ae90b4a57d92b04f48a1fdbae1ae203eaf9723c1a0"
class_hash = "0x3adb07394a41d2730a05029f72765f60863f1195540159a4ee1112b56cefbcd"
original_class_hash = "0x3adb07394a41d2730a05029f72765f60863f1195540159a4ee1112b56cefbcd"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = [
    "Position",
    "Moves",
    "DirectionsAvailable",
]
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x20e4c0cb03c44bc73e2b5a3841119b8d18a650665ca5add8939d8d8720fe0a7"
original_class_hash = "0x20e4c0cb03c44bc73e2b5a3841119b8d18a650665ca5add8939d8d8720fe0a7"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_counter_counter.json"
name = "dojo_starter::models::counter::counter"

[[models.members]]
name = "entityId"
type = "u32"
key = true

[[models.members]]
name = "counter"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4efa9133b013c420b19499d64957904b66f18668f6c3de670f4b437c3738609"
original_class_hash = "0x4efa9133b013c420b19499d64957904b66f18668f6c3de670f4b437c3738609"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_game_game.json"
name = "dojo_starter::models::game::game"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "entityId"
type = "u32"
key = false

[[models.members]]
name = "status"
type = "GameStatus"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x48af75d0b7fd9d4165c957d18fc12f63106bd91a306a8325cdd660358756e90"
original_class_hash = "0x48af75d0b7fd9d4165c957d18fc12f63106bd91a306a8325cdd660358756e90"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_health_health.json"
name = "dojo_starter::models::health::health"

[[models.members]]
name = "entityId"
type = "ContractAddress"
key = true

[[models.members]]
name = "gameId"
type = "u32"
key = true

[[models.members]]
name = "health"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xb0d2fa96616af5d754a4ef4c60f9bc42d53c42d72d03b5d7da900c274916a"
original_class_hash = "0xb0d2fa96616af5d754a4ef4c60f9bc42d53c42d72d03b5d7da900c274916a"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_move_move.json"
name = "dojo_starter::models::move::move"

[[models.members]]
name = "entityId"
type = "ContractAddress"
key = true

[[models.members]]
name = "gameId"
type = "u32"
key = true

[[models.members]]
name = "attack"
type = "u16"
key = false

[[models.members]]
name = "healing"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x68d83573a5260b386277316f7840a567ebc5a84f3c61a67063edc74c290355"
original_class_hash = "0x68d83573a5260b386277316f7840a567ebc5a84f3c61a67063edc74c290355"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "character"
type = "Character"
key = false

[[models.members]]
name = "score"
type = "u64"
key = false
